### ISSUE TITLE
In progress email step is incorrect.  Only two occur. 

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-brand-portal.en#1]
Issue in ./help/using/brand-portal-publish-contribution-folder-to-aem-assets.md

Below is incorrect, there are only two emails or notifications in BP to AEM flow.  Number 2 does not happen. 

An email/pulse notification is sent to the Brand Portal and AEM, administrator and user at various stages of the publishing workflow:
1. Queued - When publishing workflow triggers in Brand Portal, contribution folder is published from Brand Portal to AEM.
2. In-Progress - When AEM Assets begin importing the contribution folder.
3. Complete - When publish action is complete, contribution folder is successfully imported to AEM Assets.

 [Logged By Support]

**Comment by vishabhguptaadobe** [comment]
Thanks @ycastane.
I have created a ticket: CQDOC-15925.
Will fix it soon.

**Comment by vishabhguptaadobe** [comment]
Updated: https://docs.adobe.com/content/help/en/experience-manager-brand-portal/using/asset-sourcing-in-brand-portal/using-asset-sourcing/brand-portal-publish-contribution-folder-to-aem-assets.html
