### ISSUE TITLE
Folder upload is not permitted

### ISSUE THREAD

**Issue by swaroop61** [AdobeDocs/experience-manager-brand-portal.en#11]
Issue in ./help/using/whats-new.md

The "Upload assets to contribution folder" section mentions that one can upload multiple assets or folders containing multiple assets to the contribution folder (New), the screenshot shows the same "upload Files/Folders", however you cannot drag & drop a folder to upload.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by vishabhguptaadobe** [comment]
Updated at : https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/introduction/whats-new.html#upload-assets-in-bp
