### ISSUE TITLE
Missing contractual definition of Standard and Light user

### ISSUE THREAD

**Issue by ptager** [AdobeDocs/experience-manager-brand-portal.en#12]
Issue in ./help/using/brand-portal.md

Customers are not able to make the connection between the definition of Standard and Light users referenced in the Product Definition page below, and the user personas described in the section "User personas in Brand Portal"
https://helpx.adobe.com/legal/product-descriptions/adobe-experience-manager-cloud-service.html

Need to add to the doc page below the definition of AEM Assets Standard and Light users and how they can be created with their respective permissions to be able to use AEM Assets and Brand Portal.
https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/introduction/brand-portal.html?lang=en

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @ptager. We will investigate.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by vishabhguptaadobe** [comment]
Updated at: https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/introduction/brand-portal.html#guest-user
