### ISSUE TITLE
Brand Portal is also available to Adobe Experience Manager Assets as a Cloud Service 

### ISSUE THREAD

**Issue by dburwitz** [AdobeDocs/experience-manager-brand-portal.en#14]
Issue in ./help/using/home.md

The 4th paragraph is incomplete
> Brand Portal is a cloud-based SAAS offering. It is available as an add-on to Adobe Experience Manager Assets product (on premise or managed service).

Actually Brand Portal is also available to Adobe Experience Manager Assets as a Cloud Service. See [Configure Assets with Brand Portal](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/assets/brand-portal/configure-aem-assets-with-brand-portal.html?lang=en).

**Comment by raimanS** [comment]
@dburwitz Thank you for pointing this out. We will look into it.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by kkour06** [comment]
The documentation gaps have been filled and the changes are available live at https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/home.html?lang=en
cc: @anujkapo

**Comment by dburwitz** [comment]
Looking good. Please, close issue.

Thank you
Kind regards
Daniel

Daniel Burwitz  |  Senior Technical Account Manager |  Adobe


From: kkour06 ***@***.***>
Date: Tuesday, 17 October 2023 at 10:14
To: AdobeDocs/experience-manager-brand-portal.en ***@***.***>
Cc: Daniel Burwitz ***@***.***>, Mention ***@***.***>
Subject: Re: [AdobeDocs/experience-manager-brand-portal.en] Brand Portal is also available to Adobe Experience Manager Assets as a Cloud Service (Issue #14)

EXTERNAL: Use caution when clicking on links or opening attachments.



The documentation gaps have been filled and the changes are available live at https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/home.html?lang=en
cc: @anujkapo<https://github.com/anujkapo>

**Comment by guillaumecarlino** [comment]
Closing as it seems to be fixed.
