### ISSUE TITLE
Sharing and Inviting not differentiated. Description of privileges wrong.

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-brand-portal.en#15]
Issue in ./help/using/brand-portal-share-collection.md

The following chapter is wrong

"The administrators can share and unshare a collection with the authorized Brand Portal users. Editors and viewers can view and share the collections created by them, shared with them, and public collections."

Viewers can NOT share links they have been shared with themselves.  

Correct would be:
==============

Collections can be shared as  link via e-mail. Users that should be shared a collection with have to have an account on Brand Portal. Everybody with access to the share link can open the collection. Share e-mails can be forwarded to non-registered. Thus, share links are temporary, only and have a limited duration, after which they expire. Link-shared collections do not appear in the collections overview of the recipients.  

Alternatively, users can be invited as members to collections. Collections, users are invited to, are permanent and do appear in the users collection overview. 

Administrators can share and unshare a collection with  authorized Brand Portal users. 
Administrators can invite other users to a specific collection. When inviting, they can define what role that user will have on that collection.
Administrators can create public collections.

Editors can create collections and they can invite other members. In the invitation, they can define the role of the invitee.  
Editors can share collections they created. They can a also share collections, if they have been invited to the collection as Editor or Owner. Any user invited as owner on a particular collection, they can invite other users. 
Editors can not create public collections.
 
Viewers can create private collections, only. Viewers can neither share a collection nor invite other users. Viewers cannot share collections even when they were invited as owners. 

=========
This is perceived by experimentation. Please confirm with Product Management.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by dipen-sen** [comment]
One correction for "Editors can not create public collections."
In my opinion, non admin users (editors/viewers) can be allowed/prevented from creating public collections through configuration.

**Comment by ackoch** [comment]
Please add that comment to CQDOC-20773

**Comment by aheim0** [comment]
@ackoch 
@dipen-sen had kindly already added the comment to CQDOC-20773.

**Comment by kkour06** [comment]
The suggested changes are available live and accessible at https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/share/brand-portal-share-collection.html
cc: @dipen-sen @ackoch @anujkapo

**Comment by guillaumecarlino** [comment]
Closing as this was apparently fixed and the jira was closed.
