### ISSUE TITLE
Clarification Required: Assets uploaded to BP are not processed for renditions

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-brand-portal.en#2]
Issue in ./help/using/brand-portal-upload-assets-to-contribution-folder.md

There should be a statement that explains that assets uploaded to BP are not processed for renditions and hence assets do not contain previews.  

Screencaptures show video file with a preview and this leads to confusion about expected behavior.  

[Logged By Support]

**Comment by vishabhguptaadobe** [comment]
Logged a ticket: CQDOC-15927
Will address this one soon.

**Comment by vishabhguptaadobe** [comment]
docs updated: https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/asset-sourcing-in-brand-portal/brand-portal-publish-contribution-folder-to-aem-assets.html?lang=en 
https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/asset-sourcing-in-brand-portal/brand-portal-publish-contribution-folder-to-brand-portal.html?lang=en
