### ISSUE TITLE
Configuration in the replication agent for Brand Portal

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-brand-portal.en#3]
Issue in ./help/using/troubleshoot-parallel-publishing.md

As per https://jira.corp.adobe.com/browse/CQ-4273689?focusedCommentId=18159223&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18159223 the checkbox "Close connection" needs to be ticked in the "Extended" tab of replication agents for Brand Portal to avoid running in an issue where it takes long time for assets to be published.

This information should be added in the troubleshooting section

[Logged by Support]

**Comment by vishabhguptaadobe** [comment]
@clatimier,
I will check with engineering and update accordingly.

**Comment by vishabhguptaadobe** [comment]
Logged a ticket: CQDOC-16053

**Comment by vishabhguptaadobe** [comment]
Doc changes were tracked and updated in: https://jira.corp.adobe.com/browse/CQDOC-16036
