### ISSUE TITLE
Additional Detail on recommended way to filter by profile and csv restrictions 

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-brand-portal.en#4]
Issue in ./help/using/brand-portal-configure-asset-sourcing.md

More detail is required:
- on how to filter users by profile in Admin console
- csv restrictions ie. cannot import users and groups 

[Logged by support]

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @ycastane . We will have a look.

**Comment by bohnertchris** [comment]
CQDOC-16091

**Comment by vishabhguptaadobe** [comment]
Raised this to Engineering for inputs.

**Comment by vishabhguptaadobe** [comment]
Documentation updated. Raised the UI change request with Engineering.
