### ISSUE TITLE
Update documentation to reflect only users can be assigned to contribution folders

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-brand-portal.en#5]
Issue in ./help/using/brand-portal-configure-contribution-folder-properties.md

Update documentation to reflect only users can be assigned to contribution folders.  Currently #7 "In Add User or Group" as well as the UI leads to confusion that Groups assignment is supported. 

[Logged by Support]

**Comment by vishabhguptaadobe** [comment]
Let me clarify with Engineering on this and update it.

**Comment by vishabhguptaadobe** [comment]
Updated: https://docs.adobe.com/content/help/en/experience-manager-brand-portal/using/asset-sourcing-in-brand-portal/configure-contribution-folder/brand-portal-configure-contribution-folder-properties.html
