### ISSUE TITLE
Describe download behavior if Fast Download [Aspera] is enabled 

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-brand-portal.en#7]
Issue in ./help/using/whats-new.md

New Behavior: 
All the users for an Organization with Fast Download will now by default get Fast download experience without manual selection.
 
In case Fast download fails, users will be able to go via Non aspera download flow, but the default behaviour will expect user to have Aspera client setup on their machines.

**Comment by aheim0** [comment]
Thank you for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17002.

**Comment by vishabhguptaadobe** [comment]
Thanks @ycastane, @aheim0 .
I have assigned it to myself and will be addressing it in the next publish workflow.

**Comment by vishabhguptaadobe** [comment]
Updated the relevant docs:

[What's new in Brand Portal](https://docs.adobe.com/content/help/en/experience-manager-brand-portal/using/introduction/whats-new.html)

[Download assets from Brand Portal](https://docs.adobe.com/content/help/en/experience-manager-brand-portal/using/download/brand-portal-download-assets.html)
