### ISSUE TITLE
Brand Portal Download with extra folders

### ISSUE THREAD

**Issue by taylork1414** [AdobeDocs/experience-manager-brand-portal.en#8]
We just noticed that the new version of the Brand Portal automatically adds a folder for each asset during download. With our file structure this is a big issue for users. Is there a way to turn this option off? If not can you log this as a request to change this feature?

**Comment by aheim0** [comment]
Thank you for contacting us, but unfortunately this is out of scope for the documentation.

Can we please ask you to contact your support representative for such questions. Thanks in advance.
