### ISSUE TITLE
Share assets email screencapture is incorrect

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-brand-portal.en#9]
Issue in ./help/using/brand-portal-link-share.md

Share assets as link section #9.  The screencapture says 'Click to View' as a hyperlink.  This led the customer to believe either a) OOTB this hyperlink will show instead of long URL or b) You can customize this 'Click to View' text, which we haven't found in BP Admin tasks.  

Request: Correct what can be customized for the email and provide a proper screencapture. 

[1] https://experienceleague.adobe.com/docs/experience-manager-brand-portal/using/share/brand-portal-link-share.html#share

[Logged by support]

**Comment by anujkapo** [comment]
Thanks, @ycastane. We will take a look.

**Comment by anujkapo** [comment]
Tracked with CQDOC-17410.

**Comment by vishabhguptaadobe** [comment]
The URL will continue to have the label "Click to View" and will be fixed at the backend to reflect the same in the application as shown in the docs screenshot. 
This action item is not planned in any of the releases as of now. 
Therefore, no action on docs team. 
For details, refer: https://jira.corp.adobe.com/browse/CQDOC-17410
